### ISSUE TITLE
Is it still in WIP ?

### ISSUE THREAD

**Issue by frankLife** [reactide/reactide#103]
![image](https://cloud.githubusercontent.com/assets/5081884/24987424/704545e2-2032-11e7-9445-1e7de50a5d15.png)

I run `tnpm run dev-start` and `tnpm run dev`. It will show the IDE screen with some errors in console panel . I look deep into the code so that I find the reducer code seems like is still in working  like this 

>```
>const rootReducer = combineReducers({
>  // gifs: GifsReducer
>  // add reducer objects here
>});
>```

So I wonder it  still work in progress or how can I fix the problem I meet to open this great project correctly.

**Comment by basedjux** [comment]
Yes this project is still very much so WIP.
The lead devs are going creating a roadmap currently so.

**Comment by frankLife** [comment]
great ! 😄
