### ISSUE TITLE
ide can't be started!!

### ISSUE THREAD

**Issue by dandingol03** [reactide/reactide#111]
here is my operation:
1.open two tabs to run npm-script  dev and dev-start  separately.
but it seems to get sucked in the tab which runs dev-start,want your help,thanks.

**Comment by constgen** [comment]
Could you explain more clear what is `npm-script dev` and `dev-start` in your project?

**Comment by dandingol03** [comment]
@constgen  `dev` and `dev-start` in `package.json`

**Comment by constgen** [comment]
Tried your steps in VSCode. I opened 2 terminals inside the code editor and run commands in the same order as you. Nothing stacked. After 20-30 sec I saw the Electron app running on my screen.

**Comment by dandingol03** [comment]
```js
Failed to fetch extension, trying 4 more times
```
@constgen this is what i got when i run the `dev-start` in terminal

**Comment by constgen** [comment]
I use Windows and yarn.
