### ISSUE TITLE
No Download link on Reactide website...

### ISSUE THREAD

**Issue by rhlsthrm** [reactide/reactide#113]
http://reactide.io/download.html

On the website, there is no actual download link. Is the only way to run it from source?

**Comment by agupta1989** [comment]
@rhlsthrm I believe this project is in active and heavy development. So far there is no release have been made. All I can tell you to just wait and watch for few weeks (if not months) :)

**Comment by rhlsthrm** [comment]
Thanks for the info @agupta1989! I figured this was the case, and I was more referring to the confusion about the landing page.

**Comment by rounakpolley** [comment]
Yes eagerly waiting for the release

**Comment by agustif** [comment]
Still waiting, screenshots look rad, just want to use it! 🙏

**Comment by nhandyal** [comment]
Any updates on release date?
