### ISSUE TITLE
[Installation] npm install broken

### ISSUE THREAD

**Issue by quoidautre** [reactide/reactide#124]
Hi,
I'm trying to install ReactIDE, but when I use _npm install_ there's an error : 
```
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN reactide@1.0.0 No repository field.
```
and : 

```
$ npm start

> reactide@1.0.0 start /opt/reactide
> cross-env NODE_ENV=production electron .

/opt/reactide/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! reactide@1.0.0 start: `cross-env NODE_ENV=production electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the reactide@1.0.0 start script 'cross-env NODE_ENV=production electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the reactide package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs reactide
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls reactide
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/reactide/npm-debug.log
```
I'm on a VM on vagrant.

Regards,
Fabrice

**Comment by basedjux** [comment]
So the first stack is normal. That can happen with `fsevents` when it's trying to be installed on an unsupported platform (for example, Windows).

Now for the second, what are you running on your VM, OS wise?

**Comment by basedjux** [comment]
Because `libgtx-x11-*` is an X11 window server package.

**Comment by quoidautre** [comment]
Hi,
Ok for the first message.
And, yes, I'm on a VM (Ubuntu 16.04 LTS)

Thanks.

**Comment by basedjux** [comment]
Yeah if you're on Ubuntu? Yeah see if libx-x11-* has an APT package.

**Comment by quoidautre** [comment]
OK. I've installed :).. but, another error :( : 

```
$ npm start

> reactide@1.0.0 start /opt/reactide
> cross-env NODE_ENV=production electron .

/opt/reactide/node_modules/electron/dist/electron: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

```

Trying to install `libX11-xcb.*` now ?

F.

**Comment by basedjux** [comment]
What architecture is your VM? 32/64-Bit?

**Comment by quoidautre** [comment]
64 Bits

**Comment by basedjux** [comment]
You might try installing the entire GTK2 package? Instead of that one dependency.

**Comment by quoidautre** [comment]
Maybe I must install (if I not already do that) on my system ouside the VM ?

Because, I can access the files (.js) with shared folders.... isn't it ?

**Comment by basedjux** [comment]
Well yes, in some VM configs you can.
You can share the host OS' file system.

I'm not sure how you have yours configured however.

**Comment by quoidautre** [comment]
ok. I'll try tomorrow morning :)

**Comment by basedjux** [comment]
Alright! Let me know how it goes.

**Comment by quoidautre** [comment]
ok.
To be continued tomorrow :)

**Comment by quoidautre** [comment]
So, I've installed  :  
`gtk2.0`, `libxss1`, `libgconf-2-4`, and now, there's again an error :(  : 
`/opt/reactide/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: `

It's a bit annoying :(

F.

**Comment by jwebcat** [comment]
You do realize that this editor is not functional at the moment and the
project may be dead, right?

Even if you manage to get it to run it doesn't work properly, just thought
I would say that in case you were expecting something great at the end of
your efforts.

**Comment by quoidautre** [comment]
@jwebcat : No, I never say that !
I said, in my case, the IDE doesn't work, and I've a lot of errors. That's it :)


Fabrice

**Comment by jwebcat** [comment]
I know I wasnt trying to be snarky.

This project doesn't work I'm saying that. When it runs properly it doesn't
actually function.

I just didn't want you to waste your time to find out that the project is
actually not working once you finally get it to run. That's all.

- Jupiter

**Comment by simonhochrein** [comment]
I once did a project with electron on a minimal linux system and I found that there are many dependencies.
`sudo apt install libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev`
Those should be all the packages you need.

Source: https://electron.atom.io/docs/development/build-instructions-linux/

**Comment by step1step2** [comment]
````
sudo apt-get update
sudo apt-get install libx11-xcb-dev
````
Did it for me. I'm using Bash on Ubuntu on Windows. I can now move on to the next error.
#windowslaifu

**Comment by quoidautre** [comment]
Hi, 
Ok, thanks. I'll try soon.

Fabrice
