### ISSUE TITLE
Start this abandoned project again?

### ISSUE THREAD

**Issue by lokiiarora** [reactide/reactide#126]

**Comment by basedjux** [comment]
I mean, if such an undertaking _wanted_ to be done I don't see a bad reason why not.

But a new roadmap would have to be created and such.

**Comment by simonhochrein** [comment]
We should create a fork and work on that. I am very interested about helping this great project.
We could create a new organization `reactide-project`.

**Comment by SheetJSDev** [comment]
If you are interested in participating, we are attempting to coordinate a community effort at https://github.com/reactide-community/reactide

**Comment by spelunk** [comment]
If you are interested in participating, we are attempting to coordinate a community effort at https://github.com/reactide-community/reactide

**Comment by dhartford** [comment]
If can get an IDE that consistently provided good component development features such as a good live-preview option (react-component-preview or atom-react-preview) and had good i18n/accessibility/testability features (i.e. storybook with addons type equiv), and could hook/integrate/import (with same preview/testability) external components (like callme's material-ui), those three items alone would be awesome to help get junior and senior react developers greatly speed up iterations/productivity.

**Comment by simonhochrein** [comment]
Dev is taking place at https://github.com/reactide-community/reactide/tree/dev.
Contributions are welcome and we need programmers.

**Comment by ajitbohra** [comment]
@simonhochrein good to know :)

**Comment by eveningkid** [comment]
I created a project that aims to be a great react IDE. Give it a look there!
[https://github.com/eveningkid/reacto](https://github.com/eveningkid/reacto)

**Comment by EP36** [comment]
Love the support and integrity of the community. Glad to say that we are officially launching (finally) on Tuesday 8/13
