### ISSUE TITLE
State of Reactide

### ISSUE THREAD

**Issue by dhartford** [reactide/reactide#131]
Hi Team,
So could someone update the readme.md on the root of this project with the status?

I know some team members forked off to reactide-community, which then moved/rewrite to a different ide (nuclearide).

But the status and list of what is working and not working for this project is very unclear.

**Comment by EP36** [comment]
Hi @dhartford, we've added new members to the team, including myself, and we're glad to say that we will be launching 3.0 on Tuesday 8/13. You can see that the repo is currently up-to-date.

Thanks so much for the support :)
