### ISSUE TITLE
please how do i get this app runing on windows os

### ISSUE THREAD

**Issue by vincentroman** [reactide/reactide#132]

**Comment by Silverium** [comment]
have you tried in their downloads page? http://reactide.io/download.html

**Comment by wjmcdermott** [comment]
Once you have cloned the directory go it 

~\reactide\npm install
~\reactide\npm start

**Comment by Yajan** [comment]
I am getting error when I run `npm install` 
`added 1277 packages from 1608 contributors and audited 14674 packages in 188.134s
found 9 vulnerabilities (5 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details`
