### ISSUE TITLE
reactide fails to install

### ISSUE THREAD

**Issue by sdowlati** [reactide/reactide#133]
I just downloaded the latest version. Didn't install:

C:\tools\reactIDE>npm install
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sdowlati\AppData\Roaming\npm-cache\_logs\2018-04-27T15_41_35_710Z-debug.log

C:\tools\reactIDE>npm -v
5.8.0

C:\tools\reactIDE>node -v
v8.11.1

**Comment by EP36** [comment]
I suggest forking/cloning the repo and following the instructions in the readme. We will be launching 3.0 on Tuesday, 8/13 and you will be able to download the app directly from our website which eliminates the need for forking/cloning and running the terminal commands.
