### ISSUE TITLE
Not able to create new project

### ISSUE THREAD

**Issue by navneetccna** [reactide/reactide#134]
Not able to create new project or open any react project

browser console error : Cannot read property 'addEventListener'
cli error : directory found, won't overwrite

**Comment by yclive0925** [comment]
Same Here, don't have any respond in any place, opened with VS code.

**Comment by navneetccna** [comment]
No solution right now

**Comment by EP36** [comment]
So the problem with create new project is that it takes a while to spin up CRA. We have reduced bundle time and updated the UX so you know that it is loading.
