### ISSUE TITLE
Project is die?

### ISSUE THREAD

**Issue by bpGusar** [reactide/reactide#135]
Project is die? Last update has been a 4 mouth ago

**Comment by estevanjantsk** [comment]
Last commit 4months ago, so...yes. dead.

**Comment by Shawnxkwang** [comment]
But I'm interested

**Comment by Tchoupinax** [comment]
Me too. Able to focus on another repository and revive the project ? :D

**Comment by NewAlexandria** [comment]
Someone should reach out to the maintainer to discuss joining the project.  Anyone super-motived should clone and begin improvements, to demonstrate commitment. 

IMO

**Comment by jasonehle** [comment]
FYI there is a plan for React Studio to open source it sometime in the near future. Perhaps it’s worth waiting for that to happen and start with a solid base

**Comment by volkerchartier** [comment]
@jasonehle Why waiting? open the source!

**Comment by 0xc0d3r** [comment]
Guys! Any updated information about this project?

**Comment by yuritoledo** [comment]
??

**Comment by biels** [comment]
Any chance this can revive?

**Comment by exocode** [comment]
very sad to see a project like this perishing... :-/

**Comment by chriswingler** [comment]
Wouldn't it make more sense to port this to a vscode extension?

**Comment by exocode** [comment]
This would be awesome. I am not familiar in making VSC extensions. I also struggle to build the version-2 branch successfully.

**Comment by chriswingler** [comment]
After learning how to make VSC extensions this weekend, it seems like its API is currently too limited (doesn't support a right sidebar) to produce a 1:1 clone of Reactide.  It'd likely take a maintained fork of VSC to do it justice.

Reactide's UI is itself written in React, so it'd be a matter of building React components one by one, then mapping them to VSCode (the latter half probably being the hardest part with most unknowns.)

**Comment by EP36** [comment]
Thanks for the support everyone!!

We have added new members to the team, including myself, and we're glad to say that it is alive. We will be launching 3.0 Beta with lots of improvements from 2.0 on Tuesday, 8/13. You will be able to download the application directly on our website without needing to fork/clone the repo. 

All beta testers are welcome as the master branch is currently up-to-date.
