### ISSUE TITLE
Installation incorrect

### ISSUE THREAD

**Issue by mlk5060** [reactide/reactide#138]
The `READEME.md` and `package.json` files are not correct: I could not get Reactide to install and run using them. The issues are as follows:

1. No electron dependency is declared in the `package.json` file
2. It is not possible to double click on the Reactide file created after issuing `npm run electron-packager`.

I have fixed these issues and will issue a pull request shortly.

**Comment by mlk5060** [comment]
I've created a branch locally and committed my fixes, not able to push/create the branch to/on `origin` though. Any advice would be greatly appreciated!

**Comment by williamhatch** [comment]
@mlk5060 could you fork that and push the fork? thanks!

**Comment by mlk5060** [comment]
Hi there!

I'll do so this evening (GMT)? Hopefully I still have the repo on my home
computer (not used it in a while)!

**Comment by mlk5060** [comment]
@williamhatch Check out the `master` branch at https://github.com/mlk5060/reactide :smile: This works for me so hopefully will for you too!

**Comment by EP36** [comment]
We've added new members to the Reactide team, including myself, and we're glad to say that we have made major improvements on 3.0. You can see them on the master branch along with an updated readme. We will be launching the beta on Tuesday, 8/13 and you will be able to download the application directly from our webpage without having to fork/clone the repo.

Thanks for the support!!
