### ISSUE TITLE
in release-builds folder there is no executable file !

### ISSUE THREAD

**Issue by scyrencop** [reactide/reactide#139]

**Comment by EP36** [comment]
You will have to run `npm run electron-packager`
however, we are releasing 3.0 on Tuesday, 8/13 and you will be able to download the application directly from our website without having to fork/clone the repo.

**Comment by teja463** [comment]
Hey, @EP36 when the installable file is coming, Its 8/16. it would be better if you can provide an installable file instead of asking people to run command.

**Comment by asleboon** [comment]
> 
> 
> You will have to run `npm run electron-packager`
> however, we are releasing 3.0 on Tuesday, 8/13 and you will be able to download the application directly from our website without having to fork/clone the repo.

OP has run the command `npm run electron-packager` the release-builds folder is created after. Same issue for me, no executable files to be found.

**Comment by SpeedOfSpin** [comment]
If you just want to run it in dev mode you can just type
`npm start` from the root directory.

If you havent got an exe try running the packager directly with
`npx electron-packager . --overwrite --platform=win32 --arch=x64 --prune=true --out=release-builds`
