### ISSUE TITLE
Typo on the website

### ISSUE THREAD

**Issue by tiagological** [reactide/reactide#144]
Two minor typos on the features page of the website. 

Third sentence in the first paragraph. 

> This makes projects build-tool agnostic, allowing for only **necceary dependancies** to be added later as projects evolve as opposed to making decisions when the coding hasn’t even begun.

Should be **necessary dependencies**.

**Comment by EP36** [comment]
Thanks for the catch! We're updating revamping our webpage and will be launching 3.0 on Tuesday so stay tuned... :)
