### ISSUE TITLE
Error running electron-packager

### ISSUE THREAD

**Issue by ShawnCholeva** [reactide/reactide#157]
Hey guys, I was going to check out the IDE and followed the steps on the README, under "Getting Started with Reactide", to generate the executable when I ran into the following error on the step `npm run electron-packager`.  Let me know if you need more information or anything to get this fixed, or maybe it's something I am missing on my side?

![image](https://user-images.githubusercontent.com/13332685/62968332-72e57b80-bdd0-11e9-94fe-ef8104b73b63.png)

**Comment by SeemsRocky** [comment]
What OS you are running and what branch you are currently on? Otherwise one possible fix is to just get rid of the --icon part of the script in package json and see if that works

**Comment by ShawnCholeva** [comment]
64-bit Windows 10 Pro 64 bit.. I just download the zip file under Releases, specifically the Latest Release which was today "Official 3.0-beta release for Mac OS".  Removing that part of the package.json script does indeed let the script succeed, but I would assume the icon will be missing for the executable? (Not that familiar with packaging electron applications)

**Comment by SeemsRocky** [comment]
Yea i think it was a quick fix we were trying to get the icon to show up but does it work on windows for you?

**Comment by TobiasJoergensen** [comment]
Yep, removing the --icon=/Users/ep/Codesmith/reactide/icons/icon.png will work.

Doing this instead works better: --icon=icons/icon.png
