### ISSUE TITLE
Building for Windows creates a Darwin build instead

### ISSUE THREAD

**Issue by jwmickey** [reactide/reactide#160]
I'm having trouble getting a windows executable to build.  I'm on Win10, using Powershell, node 10.x.  Instead of an exe I'm getting a Reactide-darwin-x64 folder.  Relevant console output is pasted below.  Am I missing something?

```
PS C:\Users\jodym\reactide\release-builds> ls                                                                                                                                                    

    Directory: C:\Users\jodym\reactide\release-builds


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        8/13/2019  11:25 PM                Reactide-darwin-x64


PS C:\Users\jodym\reactide\release-builds> git rev-parse --short HEAD                                                                                                                            
d34870e

PS C:\Users\jodym\reactide\release-builds> [Environment]::OSVersion                                                                                                                              
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.18362.0 Microsoft Windows NT 10.0.18362.0


PS C:\Users\jodym\reactide\release-builds> node -e "console.log(process.platform)"                                                                                                               
win32                                   
```

**Comment by L0rdCr1s** [comment]
Did you get a solution for this? i'm using arch linux and i'm getting the same problem

**Comment by marcismk** [comment]
To build windows version change platform from `darwin `to `win32` in `package.json`

`"electron-packager": "electron-packager . --overwrite --platform=win32 --arch=x64 --prune=true --out=release-builds",`

**Comment by L0rdCr1s** [comment]
> To build windows version change platform from `darwin `to `win32` in `package.json`
> 
> `"electron-packager": "electron-packager . --overwrite --platform=win32 --arch=x64 --prune=true --out=release-builds",`

This worked for me, though for me i changed platform from `darwin` to `linux`

**Comment by SeemsRocky** [comment]
Sorry about the inconvenience guys! We were mainly testing our application on macOS and forgot to create other packaging for other OS. We will get that up and ready to go soon!
