### ISSUE TITLE
Suggestion: Turn this IDE into VS Code extensions

### ISSUE THREAD

**Issue by Ralms** [reactide/reactide#163]
Hi there,

Just found out about this IDE, however is a really hard sell to stop using an IDE with many other functionalities and customization just for a couple features. 

Currently it's possible to have a real time view of the end product, however the Component Tree would be a cool thing to have.

Have the team considered flipping this project into a very good VS Code extension? 

Thanks.

**Comment by EP36** [comment]
Hi @Ralms, while a VSC extension would be a neat project we are not looking to compete with VSC. We built this application with React developers in mind. The application itself builds a stronger narrative and grows us more as software engineers and that was our overall goal. You are more than welcome to take this application and turn it into a VS Code extension as this is an open source project.

**Comment by gaui** [comment]
> Hi @Ralms, while a VSC extension would be a neat project we are not looking to compete with VSC. 

This doesn't make any sense. By creating a new IDE, you are competing with VSC. Extension would not compete with them.

**Comment by Ralms** [comment]
> > Hi @Ralms, while a VSC extension would be a neat project we are not looking to compete with VSC.
> 
> This doesn't make any sense. By creating a new IDE, you are competing with VSC. Extension would not compete with them.

I'm happy to know that I'm not alone thinking this :)

**Comment by Ralms** [comment]
@EP36 I'm just providing my personal opinion.
The scope of VSC is pretty wide, from what is shown on the Reactide website, I can't see of anything you can't do in VSC. There are some pretty advanced extensions out there with previewers and everything for other scenarios. 

Also, you are requesting the same to your users in regards to the 'scope' limitation, by picking Reactide as an IDE I'm limiting myself to the scope of Reactide, being forced to abandon around 15 extensions that help on day to day :) 

Creating a side project to convert Reactide will split the community, not sure if that is the best decision. 

Just some things to consider.
