### ISSUE TITLE
reactide.config.js Couldn't Be Found

### ISSUE THREAD

**Issue by Zed-M** [reactide/reactide#164]
- ### Hey Guys! I'm running on windows 10, I couldn't build the app for the first time so I had to edit the package.json by **changing darwin to win32 && removing the icon flag**.

then When I tried "**npm run reactide-server**" I couldn't find this script in the package.json neither the **reactid.config.js** file in the release-builds

**Comment by SeemsRocky** [comment]
were there any error messages when running reactide? and did you open or create a new project?

**Comment by Zed-M** [comment]
@SeemsRocky I created a new project, the reactide created a folder with a node_modules in it and package.json but no reactide.config.js

**Comment by juanhart1** [comment]
@Zed-M Thank you for this feedback. One suggestion is to try refreshing the file directory by hitting the refresh button a few seconds after 'Create New Project' is completed. Let us know if that results in you being able to see the reactide.config.js file.

**Comment by nathandaly** [comment]
Same issue with me. Creating a project does not create a `reactide.conf.js`. One project it did appear in but was empty is that also correct?

https://streamable.com/t8yen

**Comment by SeemsRocky** [comment]
It shouldn't create a reactide.config.js when you create a new project, all you have to do is run these commnds in the terminal in reactide
```
npm install
npm start
```
and you can get it running

**Comment by erikswed** [comment]
In the picture at https://reactide.io there is a reactide.config.js in the project tree .
I run npm install , npm start, create project nothing works how do I create the reactide.config.js maybe put up a template reactide.config.js until everything starts working

**Comment by SeemsRocky** [comment]
the config file only appears when you open an existing react application. Since you’re using create new project, you should run npm start instead of npm run reactide-server.

**Comment by nathandaly** [comment]
Thanks @SeemsRocky. It would be a nice feature if it did create that with boilerplate/typical configuration.
