### ISSUE TITLE
Where is reactide-server

### ISSUE THREAD

**Issue by erikswed** [reactide/reactide#168]
I follow the setup for the simulator but cant find the script reactide-server:

> In the terminal run: npm run reactide-server

> Setting up the Simulator
> In order to take advantage of the live simulator, please follow the below steps in your project directory.
> 
> Go to the reactide.config.js file and change the .html and .js entry points to the relative path of your respective files.
> In the terminal run: npm run reactide-server
> For any questions, please look at the example project in the example folder for how to set-up webpack and dev-server.

**Comment by EP36** [comment]
Are you creating a new project?

**Comment by erikswed** [comment]
I learn React and follow this tutorial where they create a new project
https://www.valentinog.com/blog/hooks/

Liks this: npx create-react-app exploring-hooks

I open the project in Reactide

**Comment by EP36** [comment]
Apologies, when you open a new project, you don't need to run reactide-server. You can open the in-app simulator and it will begin to spin up the server. Give it a few seconds then reopen the in-app simulator and it should render properly

**Comment by erikswed** [comment]
Thanks
I open an existing project, how do I connect the simulator?

**Comment by EP36** [comment]
For existing project, you can run npm run reactide-server
