### ISSUE TITLE
No Reactide (executable) file in Reactide folder

### ISSUE THREAD

**Issue by infinite404** [reactide/reactide#174]
OS: Kubuntu 18.04
KDE Plasma Version: 5.12.8
KDE Frameworks Version: 5.44.0
QT Version: 5.9.5
Kernel Version: 5.0.0-27-generic
OS Type: 64-bit

npm version: 6.9.0
nodejs version: 10.16.3
react version: 16.9.0

**Performed steps:**

```
git clone https://github.com/reactide/reactide.git
cd reactide/
git checkout 3.0-release
npm install
npm run webpack-production
npm run electron-packager
```

> in your Reactide folder, navigate to the release-builds folder and double-click on Reactide (executable).

Nothing there, I've tried the performed steps with root privileges but nothing changed. I have also tried

`npm install react-scripts --save`

but did not help.

The message I receive is the following when I run electron-packager:

> Packaging app for platform darwin x64 using electron v3.1.13
> Wrote new app to release-builds/Reactide-darwin-x64

Any ideas? Thank you in advance!

**Comment by SeemsRocky** [comment]
Sorry about that! Just go to your package.json and change the --platform=darwin to --platform=linux and you should be able to run it! and I urge against the use of using react-scripts!

**Comment by infinite404** [comment]
> Sorry about that! Just go to your package.json and change the --platform=darwin to --platform=linux and you should be able to run it! and I urge against the use of using react-scripts!

Thank you! Solved
