### ISSUE TITLE
is Reactide still being maintained?

### ISSUE THREAD

**Issue by tohyf** [reactide/reactide#186]
Is React IDE dead?

**Comment by mastak-ua** [comment]
I can't even build it ( 3.0-release ):
![image](https://user-images.githubusercontent.com/2960469/73378464-55966200-42c9-11ea-8176-14e03a9d0a5a.png)

**Comment by mastak-ua** [comment]
It's already resolved in similar issue https://github.com/reactide/reactide/issues/184
