### ISSUE TITLE
how to install reactide in ubuntu?

### ISSUE THREAD

**Issue by bmalbusca** [reactide/reactide#200]
When I tried to execute `npm start`, after installing it, I got an error  when choosing the project folder >`... Error installing REACT_DEVELOPER_TOOLS and REDUX_DEVTOOLS extensions`. Also, it's need  3 consoles to run the ide? In order to run webpack and electron-packager

**Comment by bmalbusca** [comment]
I already figured out! I will make a pull request to update docs @EP36 . To start of getting rid of errors the #184  will help and  then executing `npm run build` after install. To use the app, I just follow the executable at `realease-builds` folder

**Comment by EP36** [comment]
Good stuff @bmalbusca
