### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by ihtml5** [reactide/reactide#38]
after yarn install/npm install, how to run this project

**Comment by Meow-z** [comment]
`
> NODE_ENV=development electron .
sh: electron: command not found
`
how to solve it？

**Comment by JiniHendrix** [comment]
hi Meow-z, you can either run the package.json script or install electron globally and run the shell command explicitly

**Comment by fand** [comment]
Electron launches before webpack-dev-server gets ready and shows empty window.
Following these steps I got the app working.

- Run `npm run dev`
- Wait until webpack-dev-server launch
- Reload the electron window

**Comment by JiniHendrix** [comment]
Yes, if you want live reload, run npm run dev in one terminal, wait for webpack server to start up,
then in another terminal run npm run dev-start.

npm start should also work, but you won't have live reloading.

**Comment by Meow-z** [comment]
thanks.

**Comment by foreggs** [comment]
When are you planning to release .exe and .DMG ?  I like this editor and I'd love to see it as a fully working and production ready project.

**Comment by JiniHendrix** [comment]
hi foreggs, we don't have a set date as to when we are releasing a .exe or .DMG as of yet. We are just beginning to tackle the component visualizer and would like to ship an install package after it is finished for beta testing. Thanks for your interest! We are working hard to get it out ASAP.
