### ISSUE TITLE
How to install documentation

### ISSUE THREAD

**Issue by atakangktepe** [reactide/reactide#42]
Maybe "How to install" section can be very helpful in Readme file. Is there any plan for this?

Thanks.

**Comment by eko24ive** [comment]
It would be nice if you could simply add #38 contents to README for now

**Comment by Pau1fitz** [comment]
@eko24ive created a pull request to include these instructions in the readme for now.

**Comment by eko24ive** [comment]
Awesome, thank you @Pau1fitz 
I hope repo owners merge it as soon as possible !

**Comment by markmarcelo** [comment]
The project is in active development and currently only running in development modes. We'll have a contributor guidelines doc soon and hope to have install packages next week.
