### ISSUE TITLE
Uncaught Error: Cannot find module '../dist/bundle.js'

### ISSUE THREAD

**Issue by capaj** [reactide/reactide#43]
I get this error when running the project
![image](https://cloud.githubusercontent.com/assets/1305378/24496940/17edd358-153a-11e7-8ad4-bc001f9d6fea.png)

**Comment by atakangktepe** [comment]
Hey,

You need two command for starting reactide correctly, once run `npm run dev` command and wait for webpack to start, then run `npm run dev-start` in another command line tab.

**Comment by ncphillips** [comment]
This should be added to the README!

I expected `npm start` to work
