### ISSUE TITLE
Support for other "frameworks"?

### ISSUE THREAD

**Issue by jbucaran** [reactide/reactide#47]
Hi, this looks amazing 👋 

Are you considering to support other frameworks in the future, maybe? :)

It would be great to benefit from Reactide's state flow visualization and other UI characteristics without being locked in to a particular framework.

**Comment by InDieTasten** [comment]
@jbucaran I think the IDEa (not even proud of this) is to focus exactly on react. It is designed to work well with react. Putting in different frameworks will make this become like any other ordinary editor, like vs code, or similar. It is impossible to create an IDE that works perfect for multiple frameworks. The workflow is too different.

**Comment by jbucaran** [comment]
Hi @InDieTasten! I know what you mean, but while some frameworks are disparaginly different, some are very similar. For example, supporting Preact should be very possible.

The same goes to frameworks that similar to React based in a virtual DOM and the state -> view -> render cycle.

**Comment by InDieTasten** [comment]
Now this makes sense to me. I would still assume, that (since this project is very young) it will continue to support react and only react with no derivatives for a while till the ide is more mature ;)

But only the owners/contributors will know. Let's see ⏳

**Comment by jbucaran** [comment]
🤞 :)

**Comment by codingphasedotcom** [comment]
Yes i think you guys should just focus on react... doing other frameworks is just going to take you guys away from your initial goal! Plus react ROCKS!

**Comment by OleksiiKryvonosov** [comment]
what about react-native?

**Comment by markmarcelo** [comment]
Sounds like a great idea for future projects. In the meantime, this project will be focused on development with React.
