### ISSUE TITLE
How do I use it with my projects?

### ISSUE THREAD

**Issue by imvetri** [reactide/reactide#51]
I followed below steps.

1. Clone the project
2. install dependencies
3. npm start 

At 3rd step I was hoping for a interactive GUI. But actual was a electron browser with no content in it. 

Can someone point me at the right direction ?

**Comment by knpwrs** [comment]
1. `yarn install`
1. `yarn dev`
1. In another terminal: `yarn dev-start`

Most electron projects that use webpack also include a script that uses [`concurrently`](http://npm.im/concurrently) so the second two steps are the same. I suggest the repo maintainers add such a script.

**Comment by imvetri** [comment]
Would the same work with npm as well?

**Comment by serdimoa** [comment]
@imvetri, yes, it's works with npm.

1. `npm install`
2. `npm run dev`
3. In another terminal: `npm run dev-start`

**Comment by imranmalik** [comment]
The above instructions should be added to README.

**Comment by bchynds** [comment]
@imranmalik: It used to be, but looks like it was removed https://github.com/reactide/reactide/commit/4f546d360e3a636842542a4e31ce8f2f46684c0a

**Comment by codingphasedotcom** [comment]
I did the same steps 
1. yarn install
2. yarn dev (one terminal)
3. yarn dev-start (another terminal)

what am I supposed to see? a todo app? it doesn't show anything? 
I get the electron window with the file tree but theres nothing showing up.



![screen shot 2017-03-31 at 2 44 06 pm](https://cloud.githubusercontent.com/assets/26421899/24564669/a987d822-1620-11e7-9de5-cb966968ab22.png)

![screen shot 2017-03-31 at 2 46 08 pm](https://cloud.githubusercontent.com/assets/26421899/24564713/db03a4c6-1620-11e7-95fe-3ca17e4b308d.png)

**Comment by blackiebrwn** [comment]
@codingphasedotcom I'm getting the same bug/errors.

**Comment by JiniHendrix** [comment]
hey guys, please note the project is still in early development. You can follow the instructions above with yarn or npm to run the current iteration. Cheers!

**Comment by henryzp** [comment]
why it not GUI?

**Comment by SC7639** [comment]
I'm having the exact same issue as @codingphasedotcom. I can start reactide but then nothing shows in the main panel. 

![reacide err](https://cloud.githubusercontent.com/assets/6049560/24576267/c1e968aa-16b0-11e7-9d11-ff0cbda81423.png)
![reacide err1](https://cloud.githubusercontent.com/assets/6049560/24576268/c1ec3562-16b0-11e7-85f3-5bc3e41b0198.png)

Thanks for your hard work so far I'm looking forward to being able to use this with a project soon

**Comment by kyriejoshua** [comment]
@codingphasedotcom I'm having the same problem when I run `npm run dev` in a terminal and run `npm run dev-start` in another terminal .

**Comment by oshalygin** [comment]
This should be in the readme file...
https://github.com/reactide/reactide/pull/60

I'm not sure I understand the logic around "this is early development" so we're going to make people open up `package.json` and figure out how to run the application or better yet, look at random issues.

But w/e good luck :)

**Comment by probablyup** [comment]
Taking a day to put together an automated installer / launcher (for macOS at least) would skyrocket the usage of this. Not sure why you folks announced it without one to be honest.

**Comment by Sharlaan** [comment]
agreed with @probablyup 

v1.0.0 should expose at least a complete readme, and a site with
- presentation
- how to install ([win-installer](https://github.com/electron/windows-installer) | i didnot find for macOS but there is this [Electron packaging page](https://github.com/electron/electron/blob/master/docs/tutorial/application-distribution.md#application-distribution))
- how to run (should implement a one-command-run-it-all, or shortcut on desktop)
- a features page showing how-to with simple examples
- how to debug and run test suites (should replace Mocha/Chai with Jest) THIS is the key feature in my humble opinion making ReactIDE above any other editor, especially state flow visualization. An example with Redux would fit as showcase.
- how to package/build/deploy

Keep in mind there is a commercial concurrent *React Studio* already much more advanced, with importing Sketch designs capabilities.

Rushing for release would risk to ruin this potentialy nice app...

**Comment by oshalygin** [comment]
@Sharlaan @probablyup I put out a PR and they closed it saying they dont want it.  I think theres an emphasis on keeping just a few devs on this and keeping the hype up.  I could be wrong and I'd love to hear otherwise.

**Comment by Hum4n01d** [comment]
:(

**Comment by markmarcelo** [comment]
The project is still in its early stages. There will be detailed instructions on setting up the development environment in the next few days. Thanks!

#35

**Comment by ethankong113** [comment]
Can we add the starting instruction to README.md? Took me a while to find this information.. almost abandoned this repo.

**Comment by SC7639** [comment]
I agree the idea is great but getting started by having to read through the issues is a put off

**Comment by ethankong113** [comment]
Does the simulator button do anything? I only get a blank simulation of HTML page. Doesn't see any React component being rendered 😢 

Also, I'd suggest moving the Simulator button to bottom right.. make it green and much bigger (perhaps a play button as well.) It's a small UX change but if everyone is going to hit that button.. it's VERY important to make it right.

**Comment by oshalygin** [comment]
This isn't really an open project so you guys trying stuff under the hood may not be how the backend or anything else for this is setup.  There's no readme documentation intentionally because they dont intend it to be public.
