### ISSUE TITLE
Add ESLint and ESLint-loader to webpack config

### ISSUE THREAD

**Issue by kulakowka** [reactide/reactide#61]
I think you should add linters at the very beginning, so that the project has a coding style.

**Comment by sergiusignacius** [comment]
Maybe use TS too?

**Comment by kulakowka** [comment]
In addition, i suggest to use [standardjs](https://standardjs.com/) for code style.

**Comment by isnifer** [comment]
I vote for airbnb

**Comment by kulakowka** [comment]
@isnifer Do you like semicolons?

**Comment by basedjux** [comment]
I'm with @kulakowka.
I vote for using standardjs code style.

**Comment by kulakowka** [comment]
<img width="1000" alt="2017-04-05 20 49 04" src="https://cloud.githubusercontent.com/assets/557190/24719144/575ae024-1a41-11e7-95b8-8495c0f334a3.png">

This is companies list who uses standardjs.

**Comment by sergiusignacius** [comment]
Don't mean to insist, but what are your guys' position on using TypeScript?

**Comment by basedjux** [comment]
@sergiusignacius TS is nice, certainly is nice for polymorphic programming and definition files, but I'm not sure on how nice it plays with Electron. 

Just seems to me like it'd be another build step.. Transpiling the TS to ES6.
Not sure it'd be worth it in my opinion.

**Comment by sergiusignacius** [comment]
There are a bunch of Electron + TS samples scattered through the webs, so it may be a question of checking if they're a good match for this project. 

Indeed, in the end, it's another step, but it does help you a lot in development. However, if the editors/IDEs you use still give you type information, then I'm happy to accommodate that (and would like to learn more about that).

**Comment by isnifer** [comment]
@sergiusignacius we don't need TypeScript.
@kulakowka we don't use semicolons at Tipsi. 
But `standardjs` is ridiculous. What standard? Who got rights them to name this package as standard? 
These companies are no matter. 
Just check a difference in downloads of [standard](https://www.npmjs.com/package/standard) and [airbnb](https://www.npmjs.com/package/eslint-config-airbnb) to understand who the most popular.
Also, you can just extend Airbnb config and rewrite some rules. Or you can create your shareable config based on airbnb like we do it in [Tipsi](https://github.com/tipsi/eslint-config-tipsi)

**Comment by sergiusignacius** [comment]
@isnifer can you explain a bit better why you think that? As I said in my comment, I'm pretty open to learning more about alternatives, and your answer is pretty generic and unsupported.

**Comment by basedjux** [comment]
@sergiusignacius I think it's because this project is already using ES6 so much, that changing over to TypeScript would be a waste of dev time.

**Comment by sergiusignacius** [comment]
Sure, I get that argument, although if you measure that against productivity in the long run then that may be an interesting discussion, instead of exchanging yes and no back and forth. Thanks.

**Comment by kulakowka** [comment]
@isnifer The ideology of standard js is not to invent rules. They have already come up for us. 

NPM does not matter? Or Github does not matter? AirBnb is just a hotel search engine. Github and NPM are the foundation of the entire front-end infrastructure. 

I vote for Standard.js

I do not have anything against AirBnb. %) Peace...

**Comment by sergiusignacius** [comment]
@kulakowka we're having all these discussions without the owners weighing in. Seems to me that we're trying to make this repo look like everyone's taste, based on subjectivity. All these discussions need to happen with them and need to be healthy, informed ones. Either it's standard js, or any other standard, or choice of dev tools needs to be weighed in, not just forced inside the project.

In my opinion, standard.js seems promising and deserves to be looked at. Arguing that no one made them leaders is a fallacy - it's the same for airbnb. This should be an informed, objective decision/discussion.

Would like to see the owners to voice their opinions, otherwise this repo will be just a bunch of people arguing what they think should be the structure of the project.
