### ISSUE TITLE
IDE isn't loading

### ISSUE THREAD

**Issue by vaporwavie** [reactide/reactide#65]
I just cloned the repo, installed the dependencies using <code>yarn</code> and ran a <code>yarn run dev</code> on it, and this is what I see:
![image](https://cloud.githubusercontent.com/assets/11232965/24568286/d2e1fad8-1637-11e7-860f-f2f6124e3e09.png)

Am I missing something?

**Comment by shamsup** [comment]
I believe you need to run `yarn dev-start` in a separate terminal which will start the IDE as mentioned in #51

**Comment by JiniHendrix** [comment]
hey guys! To start up Reactide run ```npm run dev``` in one terminal and after the webpack server loads run ```npm run dev-start``` in another terminal. yarn should work as well.

Please note that Reactide is still in early development. Cheers!

**Comment by vaporwavie** [comment]
Thanks, @JiniHendrix!

**Comment by KnowledgeGarden** [comment]
Not sure it's closed: when I run npm run dev in one terminal and npm run dev-start in a second terminal, Electron pops up and says: To run your app with Electron, execute the following command in your Console (or Terminal):
/Users/jackpark/Documents/Projects/DKR2/ReactIDE/reactide/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron path-to-your-app
The path-to-your-app should be the path to your own Electron app.

What am I missing?
