### ISSUE TITLE
Failed to create a new project

### ISSUE THREAD

**Issue by fmsouza** [reactide/reactide#66]
I just installed the dependencies, and then runned `npm run dev` in a tab and `npm start` in another. The window appeared with a dark background but with no content. When I clicked in the menu `Test` and then in `New project`, this error alert popped:

![screen shot 2017-03-31 at 17 59 36](https://cloud.githubusercontent.com/assets/1396615/24569324/f82faef8-163b-11e7-8c32-6eb8a85b4c47.png)

I'm running with Node `7.7.3` and NPM `4.1.2`.
I installed the dependencies with `yarn` in version `0.21.3`.
Then I tried to run the same commands through `yarn` and this way I managed to see it working, but still I couldn't create a new project.

**Comment by JiniHendrix** [comment]
hi there, we're currently addressing this issue and should have a solution up today.

For a temporary workaround, create an empty directory named temp in the lib folder. Cheers!

**Comment by ikzjfr0** [comment]
@JiniHendrix 
you mean /library/temp folder? It still does not work. I downloaded the project today.

**Comment by ikzjfr0** [comment]
@JiniHendrix
you mean /library/temp folder? It still does not work. I downloaded the project today.
