### ISSUE TITLE
Why npm install is ERROR?

### ISSUE THREAD

**Issue by linmiss** [reactide/reactide#70]
npm run dev ,soon,localhost:8081 have a error,process is not defined at index 13.Who can tell me this error?

**Comment by vimplus** [comment]
我也报这个错误：`Uncaught ReferenceError: process is not defined at (index):13`

**Comment by linmiss** [comment]
mac and ubuntu cann't run. cann't solve this problem

**Comment by sergiusignacius** [comment]
Hey @linmiss.

From what I could gather, React IDE isn't supposed to run in a browser. That `process` reference only makes sense in a node (in this case, electron) setting.

I'm not sure what `npm run dev` does, but running `npm run dev-start` should give you better results. Do keep in mind you have to have webpack running, as the IDE will request some js files that are only generated afterwards.

Cheers.

**Comment by linmiss** [comment]
@sergiusignacius ok,thank you. i try.
