### ISSUE TITLE
Installation & Usage Guide

### ISSUE THREAD

**Issue by williamle8300** [reactide/reactide#71]
Hi can you include an Installation Guide in the README?

I'm getting this error when I clone, and run `npm install; npm start`:

`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3`

I just have an empty black window, and none of the Mac menu items do anything.

**Comment by aneekul** [comment]
I agree. I get the exact same blank screen.

**Comment by jel111** [comment]
errors all over the place

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev-start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose config Skipping project config: /Users/macuser/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/macuser/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /Users/macuser/Desktop/Reactide
7 error Darwin 16.4.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev-start"
9 error node v6.9.1
10 error npm  v3.10.8
11 error path /Users/macuser/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/macuser/package.json'
16 error enoent ENOENT: no such file or directory, open '/Users/macuser/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by WillDent** [comment]
Deco = REACT-NATIVE
reacttide = React (web not mobile)

**Comment by jel111** [comment]
Gottcha my bad

**Comment by gailingmic** [comment]
@jel111 don't want to be harsh but this is really early in development it hasn't even had a beta release version yet. If you don't understand how to fix your error yourself then its to early for you to try using it.

**Comment by williamle8300** [comment]
I think most of us here just want a simple guide to install. That's pretty rudimentary for a README.

**Comment by KnowledgeGarden** [comment]
When I run npm run dev in one terminal and npm run dev-start in a second terminal, Electron pops up and says: To run your app with Electron, execute the following command in your Console (or Terminal):
/Users/jackpark/Documents/Projects/DKR2/ReactIDE/reactide/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron path-to-your-app
The path-to-your-app should be the path to your own Electron app.

What am I missing?

**Comment by vaporwavie** [comment]
@KnowledgeGarden you did an <code>npm i</code>, right?

**Comment by KnowledgeGarden** [comment]
npm i says something about no repository.
Removed nodemodules, did a yarn install, then everything else as yarn rather than npm. No cigar. Tries the two runs with npm again. Same issue.

**Comment by vaporwavie** [comment]
@KnowledgeGarden considering it as a bug. MacOS might be the only OS at the moment presenting this event... @JiniHendrix will probably assist you better :D

**Comment by dustintownsend** [comment]
I can confirm it works on MacOS with running Yarn, then npm run dev and npm run dev-start in another term. So, I don't think this is a bug.

@KnowledgeGarden it sounds like an issue with your npm and/or node. 
What version of NPM and Node are you running? 
If you are not familiar with Electron, then you should head over to the quickstart for Electron to start learning about how it works since this repo is still very early in development and not fully documented. https://github.com/electron/electron-quick-start

**Comment by KnowledgeGarden** [comment]
node 5.10.0 and npm 3.8.3
I suppose I should install the latest versions.

**Comment by KnowledgeGarden** [comment]
updated node and npm. Now, Electron opens with Test and a bunch of UI widgets. Not sure what to do with it, but it appears to be working (i think). Thanks!

**Comment by vaporwavie** [comment]
@KnowledgeGarden it's the actual state of the project. I don't think you can start any project with it, at least for now. But it's nice to see how the whole thing is being built! :)

@dustintownsend thanks for clarifying!

**Comment by markmarcelo** [comment]
Hi everyone,

Some of this has been discussed at #51 and #35.

**Comment by mahe7star** [comment]
Have anyone ever setup reactide successfully. cuz i'm not able to set it up

**Comment by tatiana-passarella** [comment]
After tried git clone on the repo:
fatal: could not create work tree dir 'reactide': Permission denied
???

**Comment by vaporwavie** [comment]
@tatiana-passarella if you want to use the application rather than contribute to its source, I'd suggest getting the latest build through https://github.com/reactide/reactide/releases

If your intention is to contribute to this software you should create a issue detailing what caused this git error. Personally I can't tell what's going on as this project hasn't been updated in almost a year, so I'm not aware of its current state. Cheers
