### ISSUE TITLE
Not the only one

### ISSUE THREAD

**Issue by jel111** [reactide/reactide#74]
There is another IDE for React called "Deco" (https://www.decosoftware.com) but not as Robust, I am guessing using the screenshot, because I couldn't get this to work. Deco hasn't been updated for awhile and needs a better component library but it is an IDE. I don't want this to sound rude at all. I was just letting you know because I thought it may be of some interest.

**Comment by slawek666** [comment]
Hm..

**Comment by taxmarch** [comment]
Deco IDE is for React Native (mobile app dev) and Reactide is for React (web dev)

**Comment by jel111** [comment]
My Bad!
