### ISSUE TITLE
General Use

### ISSUE THREAD

**Issue by zfrisch** [reactide/reactide#75]
Hi there!

Nice work so far! I would definitely like to contribute to this program in the future. I've gotten the document editor to open up and everything. So now I can open folders and dump it into the viewer(which is stellar by the way) but I have zero idea how the component tree-view works in the bottom left, or the manipulation pane on the top right? I wouldn't imagine that loading in the components is automated, but I couldn't find any controls to manually perform this function. I _did_ cross my fingers and tried to load my own React project, though I still didn't get anything if that makes a difference.

I've also noticed some grammatical errors and things on the main site. Is there some place I can submit edits on those?

**Comment by Hum4n01d** [comment]
I'm having the same issue :)

**Comment by FroyoAndroid** [comment]
Where to get contribution guidelines and our development road map.
There is no contribution guidelines in the repo. Please update

**Comment by markmarcelo** [comment]
Thanks for support. Some of this discussion is covered here: #35
