### ISSUE TITLE
Why is the installation still pending?

### ISSUE THREAD

**Issue by thirdj** [reactide/reactide#81]
When I install it as a yarn, I stop it from waiting in electron installation and can not proceed. 
Is it just me ..?

`
$ yarn install

yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "chai-enzyme@0.6.1" has unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
[4/4] 📃  Building fresh packages...
[1/2] ⠁ electron
[2/2] ⠁ fsevents: info ok
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
[-/2] ⠁ waiting...
`

**Comment by danielrasmuson** [comment]
It worked for me.

**Comment by Pr0x1m4** [comment]
Worked for me too.

**Comment by faddah** [comment]
+1 - i'm seeing this also, three `waiting...` messages continually spinning and never moving on from there. — Mac Pro w/ 3.5 GHz 6-Core Intel Xeon E5, 16 GB RAM, Node.JS v6.10.2 & NPM v4.4.4, your latest build on GitHub of reacted.io. why is there still no regular installer for this? your http://reactide.io site has a "Download" section, but no download link or installer there?? Please advise.

best,

—  faddah wolf
      portland, oregon, u.s.a.

**Comment by markmarcelo** [comment]
#35, #51
