### ISSUE TITLE
[Proposal] Create a simple guide "How to run"

### ISSUE THREAD

**Issue by abraztsov** [reactide/reactide#86]
It would be nice to create a simple guide about how to run the project locally.

### Why is it profitable ?
1. People will know how to work with a project
2. The number of pull requests will increase
3. The project will grow faster

For example:

## How to run locally ?

1. `yarn install`
2. `yarn run dev-start`

**Comment by life4ants** [comment]
Yes, please do this! I want to know how I can contribute to this project. Does it run in the browser for now, or is it a desktop app?

**Comment by basedjux** [comment]
@life4ants currently it has two systems:
A local electron based desktop app, then it has a webpack localhost server.

**Comment by wishinghand** [comment]
#94  Has done this.

**Comment by diegofaria** [comment]
Not exactly **this**. I think would be nice to have something like this proposal.

**Comment by markmarcelo** [comment]
#51, #35
