### ISSUE TITLE
Curious question

### ISSUE THREAD

**Issue by VladimirDev93** [reactide/reactide#87]
First of all, well done on a project like this. I've already spread the word through social media about this. This is going to help a lot of people! But I have one curious question. 
Will it have a feature like in Visual Studio, where all you need to do is to click on a component and it automatically prepares the code for you? You know for example in Visual Studio, I just have to double-click the button for example and it automatically writes the class and I'll I have to do is to write my code without writing the whole class first.

**Comment by basedjux** [comment]
Are you talking about like what XCode does? 
Where you can drag and drop action methods for UI components? Then you just write the logic for the functionality of said action?

**Comment by DrMajkrosoft** [comment]
Don't know about the XCode, sorry, I don't use Mac OS, I use Windows.
Yeah, something like that. In Visual Studio you can drag and drop a component for the application UI, then double-click on it and it automatically prepares the code that is needed for component to work and the only thing you have to do is to write logic.

https://i.stack.imgur.com/XNkmg.jpg

**Comment by basedjux** [comment]
Yeah I figured that's what you were talking about.
I would hope this project would do something like that.  Wouldn't be hard, you'd just have pre-packaged logic in a given UI component. Could be implemented 😄
