### ISSUE TITLE
Errors when trying the IDE

### ISSUE THREAD

**Issue by ptbrowne** [reactide/reactide#89]
Hi,

First of all, the Reactide project looks great and I am very interested in trying it out and maybe contribute.

I am having problems in the console and it seems a lot of components are not loaded. I checkouted the project (`e416738b`) then I did : 

```
$ yarn install
```

It seems the yarn.lock is not up-to-date since after this command, I have got 693 additions and 82 deletions according to git on the `yarn.lock` file. 

After I tried : 
```
$ yarn run dev-start
$ yarn run dev (in another tab)
```

The editor launches with the console opened and I have got this in the console : 

![image](https://cloud.githubusercontent.com/assets/465582/24699325/e67d0e10-19f3-11e7-946c-e091158962d5.png)

I must have made a mistake somewhere ?

Screenshot of the window : 

![image](https://cloud.githubusercontent.com/assets/465582/24700191/ac643106-19f6-11e7-9d1b-7a80c163993b.png)

**Comment by isnifer** [comment]
I have PRs for some errors. Vote for them - https://github.com/reactide/reactide/pulls.
