### ISSUE TITLE
[Proposal] Reactide name

### ISSUE THREAD

**Issue by DrMajkrosoft** [reactide/reactide#90]
Kind of weird calling it just "Reactide", IDE for React.js.
Maybe calling it something like "React Studio"?

There is "Visual Studio" , "Android Studio" , "Xcode" , "Xamarin" , etc.

Thought it would be good suggestion to change the name of the software product.

**Comment by andela-cdaniel** [comment]
It looks like a single word (`Reactide` instead of `React ide`) so it doesn't sound all that weird. I think the name will catch on.

**Comment by kulakowka** [comment]
@DrMajkrosoft React Studio is here https://neonto.com/reactstudio

**Comment by ritcheyer** [comment]
I personally like the name and the logo :) rock on devs.

**Comment by seanpan** [comment]
Love the logo, sense of design. Besides, the name sounds like a single word, quite reasonable.

**Comment by DrMajkrosoft** [comment]
Hah, I see the dislikes. I wasn't trying to be negative, I was just suggesting. Also, I didn't knew that there is already "React Studio" for Mac.

**Comment by markmarcelo** [comment]
I'm sure there's some great names out there but it looks like we're sticking with Reactide. Thanks for the feedback!
