### ISSUE TITLE
Was this project an april fools ? Doesn't work on windows or mac?

### ISSUE THREAD

**Issue by codingphasedotcom** [reactide/reactide#91]
I'm really curious was this an april fools joke? did anyone get this to work? Not trying to be an a-hole to the creators if this is a real project I tried windows and mac and none of them work. This is a problem with most projects on github everyone is giving this project stars but the project don't work yet.... so why are people giving it a star? give it a star once it works if its real....

**Comment by basedjux** [comment]
No this is a serious project. 
It's just super early in development, so it's fairly non-functional at the moment.

**Comment by makenova** [comment]
@codingphasedotcom lol. After building this project locally(just the master branch), I get why you would ask that question.
But like @basedjux said, it's an early project and I'll add, an ambitions one.
I think it's best to be supportive at this point because if it works out, it'll be an amazing and helpful tool.

**Comment by canoc62** [comment]
install electron fool

**Comment by alex-bezek** [comment]
Does anyone know why this project exploded so heavily right now? I saw it on twitter like alot of people i'm sure and it has achieved a ton of traction sense http://www.timqian.com/star-history/#reactide/reactide
It seems it just wasn't ready, so I wonder if it had an official announcement or was just found? Seems like a great project and I'm excited. Just curios

**Comment by hit1st** [comment]
@alex-bezek awesome observation.  There has been no official announcement, but there have been some small articles stating that it's here.  The traction comes from the fact that these talented developers have identified a serious need in the react community and has chosen to address that need.  It is still in early development, and we should give them the time and opportunity for further development of this project.  -cheers

**Comment by codingphasedotcom** [comment]
@basedjux I'm glad I really thought this was another troll project.

@alex-bezek yea I believe someone told somebody about it and then people started posting to blogs lol but it makes no sense no one has it working so what was the point of promoting it so hard. @makenova I love supporting but my only issue is the article that brought me here talked about it as if its really a working project. 

This is like me saying "Hey I just created a flying car" and people start creating articles like "Finally Cars Fly" but when people get there all that I have is a steering wheel... I really think this is one of the downsides of github anyone can make a project and somehow it gets trending without people even checking the project.

I'm just saying as a creator and developer.... Don't share a project to bloggers if you know all you have is an idea because now there's a higher expectation and even if it don't work the only person that knows about it is you. It's cool to get recognition and know if people are interested in what you are going to build but this is not the right way to do it.

**Comment by njtrettel** [comment]
Just to add to the discussion...

I just found this in GitHub's trending page (it's the top one this week). I LOVE the idea for this project, and I hope I'll be able to contribute. Currently I'm using `gedit` for React development...

**Comment by codingphasedotcom** [comment]
@njtrettel whats gedit?

**Comment by njtrettel** [comment]
@codingphasedotcom It's just the linux default text editor

**Comment by AdrianoCahete** [comment]
> so why are people giving it a star?

To track project (without receiving all the types of notifications)? To tell the creators it's good idea and people want to see more?
The star isn't just for "real projects"...

**Comment by markmarcelo** [comment]
Hi everyone. Some of this is discussed in #35.

**Comment by brandondrew** [comment]
@codingphasedotcom starring a project is a way of expressing interest.  It's not a rating system.
