### ISSUE TITLE
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6

### ISSUE THREAD

**Issue by javidhsueh** [reactide/reactide#93]
I built this locally and got error:
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.0.41/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 6

node: v6.10.0
npm: 4.0.5

**Comment by brentmulligan** [comment]
@javidhsueh Did you build the JS bundle first? I had the same issue but noticed it was just missing the bundle. If you run `npm run dev` and then `npm run dev-start` it works. It's not production ready but it's on it's way.
