### ISSUE TITLE
For anyone curious, how to use Reactide in the current state

### ISSUE THREAD

**Issue by Kocisov** [reactide/reactide#94]
Hello,

if you want to use `reactide` as it is now, you will need to do few more steps.

1. Clone `reactide` repo
   * `git clone https://github.com/reactide/reactide.git`
   * `cd ./reactide`
2. Install dependencies
   * `yarn` or `npm install`
3. Create production build npm script and run it (or just use webpack in root of `reactide` repo)
```json
"scripts": {
   "...": "...",
    "build": "webpack -p"
}
```
4. After running webpack, you should have new `dist` folder inside your repo
5. Finally, you can start `reactide` with `yarn start` or `npm run start` script
6. Reactide opens and if you open devtools, it should not have any errors
![screen shot 2017-04-07 at 10 46 21](https://cloud.githubusercontent.com/assets/7074196/24792753/9976c66e-1b7f-11e7-9ed6-b3651d3ad7a2.png)
7. Now, probably everything you can do is `Create New Project` which can be located in MenuBar
![screen shot 2017-04-07 at 10 43 39](https://cloud.githubusercontent.com/assets/7074196/24792791/be772b70-1b7f-11e7-8caa-3cf90f1bbfa1.png)
8. And then, it looks something like this
![screen shot 2017-04-07 at 10 49 59](https://cloud.githubusercontent.com/assets/7074196/24792853/ffb8209e-1b7f-11e7-8b6e-8d670cd31bd6.png)

**Comment by merlinpatt** [comment]
Are the component inspector and tree supposed to work or are they just mocked at the moment?

**Comment by Kocisov** [comment]
It's probably not supposed to work at the moment.

**Comment by markmarcelo** [comment]
Please see #51 and #35.

**Comment by shorif2000** [comment]
how about in windows?

**Comment by Kocisov** [comment]
It's dead. Anyway, it's the same thing on Windows. The menubar will be visible under the window title.

**Comment by jacoy** [comment]
This project is dead?
