### ISSUE TITLE
webpack 2 configuration

### ISSUE THREAD

**Issue by agpt** [reactide/reactide#99]
I believe webpack 2 now has slightly different syntax than what we had in webpack 1. e.g. module.loaders are now module.rules.

Ref. https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

**Comment by jeantoledo** [comment]
Can i get this issue?

**Comment by jeremy-brooks** [comment]
Is this related to the error that I am getting when running `npm run webpack` where it is complaining about the `monaco-editor` module saying `Module parse failed` and it was specifically at the `getModule` method?

**Comment by Marc-Dalmau** [comment]
Hi, I have exactly the same issue that @jeremy-brooks.

I'm using Mac OS X, and last version of npm and webpack 2.

**Comment by EP36** [comment]
We have made a universal config for 3.0. Check it out! :)
